[book]
authors = ["Aaron"]
language = "en"
multilingual = true
src = "src"
description = "Keep Knowledge Updating"
title = "dev-note"

[output.html]
cname = "tek.adaoalive.com"

[output.html.fold]
enable = true    # whether or not to enable section folding
level = 0

[output.html.playground]
editable = false         # allows editing the source code
copyable = true          # include the copy button for copying code snippets
copy-js = true           # includes the JavaScript for the code editor
line-numbers = true     # displays line numbers for editable code
runnable = true          # displays a run button for rust code